[config]
set_wallpaper = true
wallpaper_tool = 'Swww'
swww_options = [
  "--transition-type",
  "center",
]

[config.custom_keywords]
test = "aaaa" # Used as {{test}} in templates

[templates.name1]
input_path = "../colors.whatever-extension"
output_path = "~/.config/hello/colors-generated.whatever-extension"
colors_to_compare = [
    { name = "black", color = "#000000" },
    { name = "red", color = "#ff0000" },
    { name = "maroon", color = "#800000" },
    { name = "yellow", color = "#ffff00" },
    { name = "olive", color = "#808000" },
    { name = "lime", color = "#00ff00" },
    { name = "green", color = "#008000" },
    { name = "aqua", color = "#00ffff" },
    { name = "teal", color = "#008080" },
    { name = "blue", color = "#0000ff" },
    { name = "navy", color = "#000080" },
    { name = "fuchsia", color = "#ff00ff" },
    { name = "purple", color = "#800080" },
]
compare_to = "{{colors.primary.default.hex}}"
hook = 'echo "source color {{colors.source_color.default.hex}}, source image {{image}}, closest color {{closest_color}}"'

[config.custom_colors]
my_green = "#00FF00" # Used as {{colors.my_green}} in templates
my_red = "#FF0000"
my_blue = { color = "#0000FF", blend = false }
